---
- name: Prepare environment with i3-wm
  hosts: "{{ target_host }}"
  vars_prompt:
    - name: target_host
      prompt: Target host
      private: false
  vars_files:
    - vars/ssh_keys.yml
    - vars/common.yml
  tasks:
    - name: Prepare Ubuntu-based environment with i3-wm
      ansible.builtin.include_role:
        name: ubuntu
      when: ansible_facts["os_family"] == "Debian"
      
    
    - name: Prepare Arch-based environment with i3-wm
      ansible.builtin.include_role:
        name: arch
      when: ansible_facts["os_family"] == "Archlinux"

