---
- name: Copy config files zip
  ansible.builtin.copy:
    src: config.zip
    dest: "/tmp"
    mode: "0744"

- name: Extract config files
  ansible.builtin.unarchive:
    src: "/tmp/config.zip"
    dest: "{{ user_home }}"
    remote_src: true
