---
- name: Create .config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    state: directory
    mode: "0755"

- name: Create .themes directory
  ansible.builtin.file:
    path: "{{ user_home }}/.themes"
    state: directory
    mode: "0755"

- name: Create .icons directory
  ansible.builtin.file:
    path: "{{ user_home }}/.icons"
    state: directory
    mode: "0755"