---
- name: Copy Font Awesome icons zip
  ansible.builtin.copy:
    src: TTF.zip
    dest: "/tmp"
    mode: "0744"
  become: true

- name: Extract Font Awesome icons
  ansible.builtin.unarchive:
    src: "/tmp/TTF.zip"
    dest: "/usr/share/fonts/"
    remote_src: true
  become: true