- name: Install neccesary dependencies
  ansible.builtin.apt:
    pkg:
      - i3-wm
      - rofi
      - polybar
      - picom
      - neofetch
      - htop
      - alacritty
      - git
      - feh
      - bat
      - redshift
      - virtualbox
      - direnv
      - lxappearance
    update_cache: true
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: "{{ user_home }}/.config"
    state: directory
    mode: '0755'

- name: Clone polybar-themes repo
  ansible.builtin.git:
    repo: 'https://github.com/adi1090x/polybar-themes'
    dest: "{{ user_home }}/polybar-themes/"
    depth: 1
    version: master

- name: Launch polybar setup.sh
  ansible.builtin.command: "{{ user_home }}/polybar-themes/setup.sh"
  changed_when: false
  args:
    stdin: "1"
    chdir: "{{ user_home }}/polybar-themes/"

- name: Delete polybar-themes repo
  ansible.builtin.file:
    path: "{{ user_home }}/polybar-themes"
    state: absent

- name: Copy initial background image
  ansible.builtin.copy:
    src: initial_bg.png
    dest: "{{ user_home }}/Downloads"
    mode: "0744"

- name: Set initial background
  ansible.builtin.command: "feh --bg-scale {{ user_home }}/Downloads/initial_bg.png"
  changed_when: false
  environment:
    DISPLAY: :0

- name: Import tasks
  ansible.builtin.import_tasks: install_zsh.yml

- name: Install Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- name: Import tasks
  ansible.builtin.import_tasks: install_vs_code.yml

- name: Import tasks
  ansible.builtin.import_tasks: install_vagrant.yml

- name: Copy config files
  ansible.builtin.copy:
    src: config.zip
    dest: "{{ user_home }}"
    mode: "0744"

- name: Extract config files
  ansible.builtin.unarchive:
    src: "{{ user_home }}/config.zip"
    dest: "{{ user_home }}"
    remote_src: true

- name: Delete config zip
  ansible.builtin.file:
    path: "{{ user_home }}/config.zip"
    state: absent
