---
- name: Install distro dependencies
  ansible.builtin.import_tasks: install_dependencies.yml

- name: Configure i3
  ansible.builtin.import_tasks: configure_i3.yml

- name: Install GTK theme
  ansible.builtin.import_tasks: install_gtk_theme.yml

- name: Copy config files
  ansible.builtin.import_tasks: copy_config_files.yml

- name: Copy SSH keys
  ansible.builtin.import_tasks: copy_ssh_keys.yml
