---
- name: Clone polybar-themes repo
  ansible.builtin.git:
    repo: "https://github.com/adi1090x/polybar-themes"
    dest: "/tmp/polybar-themes/"
    depth: 1
    version: master

- name: Launch polybar setup.sh
  ansible.builtin.command: "/tmp/polybar-themes/setup.sh"
  changed_when: false
  args:
    stdin: "1"
    chdir: "/tmp/polybar-themes/"

- name: Copy initial background image
  ansible.builtin.copy:
    src: ../../shared/files/initial_bg.png
    dest: "{{ user_home }}/Downloads"
    mode: "0744"

- name: Set initial background
  ansible.builtin.command: "feh --bg-scale {{ user_home }}/Downloads/initial_bg.png"
  changed_when: false
  environment:
    DISPLAY: :0

- name: Remove i3lock default package
  community.general.pacman:
    name: i3lock
    state: absent
  become: true

- name: Install i3lock-color AUR dependency
  kewlfft.aur.aur:
    use: makepkg
    name: i3lock-color
    update_cache: true
