---
- name: Delete Dracula theme old directory
  ansible.builtin.file:
    path: "{{ user_home }}/.themes/Dracula"
    state: absent

- name: Download Dracula color theme zip file
  ansible.builtin.get_url:
    url: https://github.com/dracula/gtk/archive/master.zip
    dest: "/tmp/dracula-theme.zip"
    mode: "0744"

- name: Ensure Dracula theme directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.themes/Dracula"
    state: directory
    mode: "0755"

- name: Extract Dracula color theme zip file
  ansible.builtin.unarchive:
    src: "/tmp/dracula-theme.zip"
    dest: "{{ user_home }}/.themes/Dracula"
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Install Papirus icon theme
  community.general.pacman:
    name: papirus-icon-theme
    state: present
  become: true
