---
- name: Install distro dependencies
  ansible.builtin.import_tasks: install_dependencies.yml

- name: Configure bluetooth
  ansible.builtin.import_tasks: configure_bluetooth.yml

- name: Configure i3
  ansible.builtin.import_tasks: configure_i3.yml

- name: Install GTK theme
  ansible.builtin.import_tasks: install_gtk_theme.yml
