---
- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    mode: "0700"

- name: Copy SSH private key
  ansible.builtin.copy:
    content: "{{ user_ssh_private_key }}"
    dest: "{{ user_home }}/.ssh/id_rsa"
    mode: "0600"

- name: Copy SSH public key
  ansible.builtin.copy:
    content: "{{ user_ssh_public_key }}"
    dest: "{{ user_home }}/.ssh/id_rsa.pub"
    mode: "0644"
